# Generated by Django 3.0.2 on 2020-01-13 14:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 13, 14, 42, 23, 687584, tzinfo=utc)),
        ),
    ]
